[package]
name = "ss-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Serial Studio Tauri 桌面壳"

[[bin]]
name = "ss-tauri"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ss-core = { workspace = true }
ss-server = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tauri = { version = "2", features = ["devtools"] }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hex = "0.4"
bytes = "1"
serde_json = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Console"] }
